CREATE DATABASE IF NOT EXISTS REGISTER_VALIDATION; 
USE REGISTER_VALIDATION; 
CREATE TABLE IF NOT EXISTS register(
	idUser INT NOT NULL AUTO_INCREMENT, 
	User VARCHAR(100) NOT NULL,
	Passwd VARCHAR(100) NOT NULL, 
	Email VARCHAR(100) NOT NULL,
	PRIMARY KEY (idUser)
); 


